### ISSUE TITLE
this._resetCurrentTransform is not a function

### ISSUE THREAD

**Issue by NaniNoah** [pixolith/fabricjs-customise-controls-extension#83]
Sorry this happened to me
How can i fix this problem?

### customiseControls.js:451 Uncaught TypeError: this._resetCurrentTransform is not a function
    at klass._setupCurrentTransform (customiseControls.js:451:1)
    at klass.__onMouseDown (fabric.js:12142:1)
    at klass._onMouseDown (fabric.js:11751:1)

```
if (typeof action === 'object') {
        if (Object.keys(action)[0] === 'rotateByDegrees') {
          this._rotateByDegrees(e, target, action.rotateByDegrees);
        }
      }
      this._resetCurrentTransform();
```
Thx

**Comment by NaniNoah** [comment]
I change fabric version to v2.2.0 
but still some problem 

`Uncaught TypeError: fabric__WEBPACK_IMPORTED_MODULE_3__.fabric.Control is not a constructor`

```
if (target.measureTools !== MeasureToolType.RightTriangle) {
            target.controls.flipControl = new fabric.Control();
        }
```

**Comment by DineshCodeFlow** [comment]
Same issue _resetCurrentTransform  is not a function

**Comment by MDSLKTR** [comment]
Probably using this with a way too new version of fabric.js. Also fabric supports customizing your controls by default now

**Comment by ezwardChou** [comment]
Hello, I have encountered the same problem. Because of this issue, I am unable to stretch and resize my image layers.

`Uncaught TypeError: this._resetCurrentTransform is not a function`
`Uncaught TypeError: this.actionIsDisabled is not a function`

**Comment by ezwardChou** [comment]
> Same issue _resetCurrentTransform is not a function

hi, did you solve this problem?

**Comment by ezwardChou** [comment]
> > Same issue _resetCurrentTransform is not a function
> 
> hi, did you solve this problem?

I have solved this problem. The root cause is that the official fabricjs file conflicts with the fabricjs file that comes with this library. Just remove the official file.
